### ISSUE TITLE
No separate URL for 'pending' version of a graph

### ISSUE THREAD

**Issue by Arachnid** [graphprotocol/support#1]
This means that on every reload, it defaults back to the current version, and I have to select 'pending' again. It'd be nice if this were persisted in the URL.

**Comment by Jannis** [comment]
Yep, absolutely.

**Comment by Jannis** [comment]
This has been implemented for a while. The explorer now adds `?version=pending`  / `?version=current` when you switch between versions and automatically shows the right version when you refresh.
