### ISSUE TITLE
Suggestion: Ability to filter the log by full-text search

### ISSUE THREAD

**Issue by fubhy** [graphprotocol/support#10]
It would be really cool to be able to filter the logs on thegraph.com with a full-text search. I am assuming you are using an ELK stack (or similar)? If so, this could greatly improve the developer experience when trying to hunt down errors on a mainnet deployment.

**Comment by Jannis** [comment]
@nenadjaja Right now we only match full words, is that correct?

**Comment by Jannis** [comment]
This has been done for a while.
