### ISSUE TITLE
Trying again after eth_call RPC call for block #773384 - Arbitrum

### ISSUE THREAD

**Issue by rafinskipg** [graphprotocol/support#100]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Hello , i have redeployed this graph several times, but it keeps getting stuck at 2.2%. Te graph getting stuck on arbitrum-one at specific block all the time. 

https://thegraph.com/hosted-service/subgraph/rafinskipg/castles-arbitrum-v0?selected=logs

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

See the link above

**What is the expected behavior?**

The indexing should continue

**Comment by azf20** [comment]
Hi @rafinskipg it looks like your subgraph is spending a lot of time on `eth_calls`, that is not recommended for indexing performance. It also seems to still be indexing right now, but it hasn't reached the block you mention. You can get more information about the failure if it fails by following [this documentation](https://thegraph.com/docs/en/deploying/deploying-a-subgraph-to-hosted/#checking-subgraph-health). Please [join our Discord](https://discord.gg/vtvv7FP) (#hosted-service) for more help with debugging

**Comment by rafinskipg** [comment]
@azf20 

The graph is still blocked, it never passes 2.2% of the indexation
![image](https://user-images.githubusercontent.com/1152768/199971079-34282d94-0ca9-47a8-816b-a31ea7e4a18f.png)

Could you reopen this issue? It seems like a timeout with the RPC. 

I have also been posting under the hosted-service for a couple of days

**Comment by azf20** [comment]
👍 Transferred as this isn't a Graph Node bug, it's an issue with the provider on the Hosted Service. The subgraph isn't failing, we are just seeing timeouts on the `eth_call` so indexing is very slow. @incrypto32 is looking into this

**Comment by incrypto32** [comment]
@rafinskipg I'm working with our RPC provider to resolve this issue asap. Their arbitrum nodes seems to be timing out when fetching large onchain metadata

**Comment by rafinskipg** [comment]
> provider to resolve this issue asap. Their arbitrum nodes seems to be timing out when fetching large onchain metadata

thank you for the response @azf20 and @incrypto32 

I have been thinking if there's a way i can do the graph less dependant on eth_calls but i don't see much of a solution. There's another method in the contract called traitsOf that returns a JSON and i could probably use that but i have to figure out how to parse and access the data correctly using assemblyscript.

The source code for the graph: https://github.com/CastleDAO/subgraphs/tree/master/castledao-castles-arbitrum

**Comment by incrypto32** [comment]
Closing as this issue is resolved now
