### ISSUE TITLE
Add support for Goerli testnet

### ISSUE THREAD

**Issue by Arachnid** [graphprotocol/support#18]
It's all the rage.

**Comment by Jannis** [comment]
Support for Görli is now available on the hosted service, albeit without tracing support. @olibearo We can't commit to a time for when tracing for Görli will be available yet, right?

**Comment by ghost** [comment]
Right now we are waiting for Alchemy to add a Goerli endpoint for us, they don't currently support it.

We could spin up our own tracing archive node on Goerli if we need to.

**Comment by Jannis** [comment]
@Arachnid Is this a blocker for you? If not, I'd prefer limiting Görli support to event handlers for the moment.

**Comment by Arachnid** [comment]
Nope, I'm happy with only event handlers.

**Comment by Jannis** [comment]
Great! Let's close this issue then. We'll add block/call handler support for more test nets on the hosted service soon.
