### ISSUE TITLE
Bug: _contains suffix does not work

### ISSUE THREAD

**Issue by informartin** [graphprotocol/support#23]
Hi,

I would like to filter attributes on substrings. Therefore, I would like to use the _contains suffix like this in an example for the ENS subgraph: `domains(where: {name_contains: "ether"})`.
However, nothing is found using that suffix. The _starts_with suffix seems to work as expected though.

Would be cool if that was fixed as especially for matching ENS names, the graph could be very beneficial I think.

Cheers,
Martin

**Comment by Jannis** [comment]
Fixed as of graphprotocol/graph-node#1015.

**Comment by Jannis** [comment]
The fix will be available on the hosted service within the next 15 minutes.
