### ISSUE TITLE
Hosted service: GraphQL playground not working for pending subgraph

### ISSUE THREAD

**Issue by iherger** [graphprotocol/support#24]
In the hosted service, the playground for a pending (i.e. not yet fully synced) subgraph is currently querying the the deployed subgraph, not the pending subgraph.

Additionally, the addresses for the GraphQL endpoints for queries and subscriptions for the pending subgraph are not displayed; instead, the addresses for the deployed subgraph are displayed.

Querying the pending subgraph through `https://api.thegraph.com/subgraphs/id/<id>` is still possible.
<img width="1742" alt="Screenshot 2019-07-02 at 07 28 58" src="https://user-images.githubusercontent.com/36133712/60515461-f2653280-9cdb-11e9-9a19-1fde440ec578.png">

**Comment by nenadjaja** [comment]
Thanks for reporting @iherger ! I'll look into it today

**Comment by iherger** [comment]
This doesn't seem to be fixed yet.
