### ISSUE TITLE
Suggestion: ability to filter related entities in the GraphQL API

### ISSUE THREAD

**Issue by iherger** [graphprotocol/support#25]
In the GraphQL API, filtering is currently possible on root entities, but not on related entities.

Other arguments (like `orderBy`) are available on all levels. 

It would be great to also have the ability to filter on related entities, e.g.  
```GraphQL {
  investor(id: "0x1234....") {
    investmentRequests (where: { status: "PENDING" }, orderBy: requestTimestamp) {
      fund {
        name
      }
      requestTimestamp
      status
      shares
      amount
      updateTimestamp
    }
  }
}

**Comment by Jannis** [comment]
I believe this is a bug and the `where` filter is just not included in the generate API schema, even though it should be.
