### ISSUE TITLE
[Feature Request] support abi parameter decoding

### ISSUE THREAD

**Issue by jgeary** [graphprotocol/support#27]
If an event emits a bytes `data` like `'0x000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000ea000000000000000000000000000000000000000000000000000000000000000848656c6c6f212521000000000000000000000000000000000000000000000000'` and a string `ABI` like `'(string,uint256)'`, I'd like to be able to decode `data` via the `ABI` to get `{ '0': 'Hello!%!', '1': '234' }`.

see https://web3js.readthedocs.io/en/v1.2.0/web3-eth-abi.html#decodeparameters for more. This will allow me to use graph protocol with my contracts that use an upgradeable factory / registry pattern.

**Comment by Jannis** [comment]
@jgeary I agree that would be useful.

A first sketch of what this could look like:

```typescript
let result = ethereum.abiDecode('(string,uint256)', event.data)
if (result.isOk()) {
  let values = result.unwrap()
  let s = values[0].toString()
  let n = values[0].toBigInt()

  // do something with `s` and `n`
} else {
  let err = result.unwrapErr()
  log.warning('Failed to decode event data: {}', [Value.fromString(err)])
}
```

**Comment by jgeary** [comment]
hey @Jannis you mentioned in discord that this would pretty easy to expose given that it's already being done for parsing events etc. if you could point me in the right direction as to where in the codebase this happens then i would like to see if i can get it working for my purposes (and would even be happy to make a PR if i get far enough with it).

**Comment by Jannis** [comment]
@jgeary Hey! Sorry, I completely missed your comment. Are you still interested in working on it?

**Comment by jgeary** [comment]
@Jannis sure!

**Comment by gjeanmart** [comment]
Hey,
Any ETA on this one?
thanks

**Comment by itirabasso** [comment]
Is there any plan to support this?

**Comment by milonite** [comment]
The support for abi.encode/encodePacked is still in the plans?

**Comment by leoyvens** [comment]
Done in https://github.com/graphprotocol/graph-node/pull/2348, however not for the packed versions, those are harder because the ethabi crate does not support it.
