### ISSUE TITLE
Access to data source and subgraph meta data from mappings

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/support#3]
It is important that mappings have access to the contract address and other information from the data source or subgraph, especially in dynamically created data sources where the address isn't known upfront. 

From the CoinList hackathon:

> **fuhby / Today at 14:56**
> Assuming I am adding a block handler in a dynamic data source, it would be great to get the address of the data source in the blockHandler mapping so I can e.g. update a value on each block.

**Comment by fubhy** [comment]
I just ran into this again. Use-case: I want to add a block handler on a dynamic data source to make a call on the contract on every block (to store historical information over time) .

**Comment by leoyvens** [comment]
This issue seems particular to block handlers, we could add the contract address to the input data.

**Comment by fubhy** [comment]
@leodasvacas Yes, block handlers. Just the address would indeed be enough for now.
