### ISSUE TITLE
Add support for POA Network

### ISSUE THREAD

**Issue by sistemico** [graphprotocol/support#36]
Some projects, which are not yet on mainnet, make use of the [POA Network](https://poa.network/) to provide deployments of alpha o beta versions of their contracts before the release to mainnet. This is the case of the [Audius project](https://github.com/AudiusProject/audius-protocol/tree/master/contracts).

I've been working on a subgraph for Audius and using a local TG node pointing to a POA node without problems during development. But hosted service still doesn't support POA, so I'm not able to deploy it to hosted service and list it in the Explorer.

It would be great to have support to POA [1][2] in the hosted service to be compatible with the workflow of projects like Audius.

[1] poa:https://core.poa.network (Core)
[2] sokol:https://sokol.poa.network (Testnet)

**Comment by Jannis** [comment]
Done. The hosted service now supports POA Core via
```yaml
network: poa-core
```

**Comment by andogro** [comment]
Hello - I was trying to test this functionality by following the Creating a Subgraph Project instruction from an existing contract but poa-core not coming up as an option through cli. 
<img width="277" alt="cli_option" src="https://user-images.githubusercontent.com/14284654/68145814-daa0f380-fef3-11e9-8f20-196238efaaa7.png">

**Comment by Jannis** [comment]
@andogro Good catch! We forgot to update CLI.

**Comment by Jannis** [comment]
https://github.com/graphprotocol/graph-cli/issues/383 has been merged but we haven't made a new release yet.

**Comment by Jannis** [comment]
@andogro We've just released graph-cli 0.16.1, which has support for `--network poa-core` in `graph init`. That completes our support for POA Core across all components.
