### ISSUE TITLE
Hosted subgraph error should include txn hash

### ISSUE THREAD

**Issue by jjgonecrypto** [graphprotocol/support#38]
When errors occur during hosted subgraph processing, errors like the below are missing the transaction hash which caused the issue. This is a tiny fix that would prevent users from having to look up the failing block on a block explorer and hunt through the transactions to find the likely culprit.

![image](https://user-images.githubusercontent.com/799038/67580698-c2232300-f714-11e9-91fc-1c8438b31df1.png)

cc @Jannis

**Comment by jjgonecrypto** [comment]
Ugh - again.

```
Subgraph instance failed to run: Failed to process trigger: Failed to handle Ethereum call with handler "handleIssueMaxSynths": Mapping aborted at ~lib/@graphprotocol/graph-ts/index.ts, line 1404, column 4, with message: Call reverted, probably because an `assert` or `require` in the contract failed, consider using `try_debtLedger` to handle this in the mapping., code: SubgraphSyncingFailure, id: QmVLMH34LovRnpQexKUegxSe1H3CbCzVkxzgfCLuVHDuaC
```

and I have to look through 150 txns: https://etherscan.io/txs?block=8964880

**Comment by Jannis** [comment]
@justinjmoses Sorry this is causing frustration. You're right, it should be a simple change. @fordN has offered to take a look at it today.

**Comment by ghost** [comment]
@justinjmoses We deployed an update which will include the transaction hash in the log when the subgraph fails, thanks for reporting this
