### ISSUE TITLE
Call handler defined in Data Source Template not being executed

### ISSUE THREAD

**Issue by lmcorbalan** [graphprotocol/support#42]
The call handler defined here https://github.com/protofire/maker-governance-subgraph/blob/track-DssLaunchSpell/subgraph.yaml#L177 is not being triggered.

The instance of the template is being created here https://github.com/protofire/maker-governance-subgraph/blob/track-DssLaunchSpell/src/mappings/DSChief.ts#L402.

And this is the tx where the smart contract function is being executed: https://etherscan.io/tx/0xa418049bc3d4f8d34678fdefb5c5cab66ce8f3650cdb0d11f3f56bb145bdbc55

**Comment by Jannis** [comment]
@olibearo Has this been rolled out?

**Comment by ghost** [comment]
Yes, it has been deployed to production
