### ISSUE TITLE
Support for Node 12.x

### ISSUE THREAD

**Issue by That3Percent** [graphprotocol/support#46]
The current LTS version of Node that is required by codegen is Node 10.x. Attempting to go through the [Quick Start](https://thegraph.com/docs/quick-start) using Node 12.x fails on the step `yarn & yarn codegen` with the following:

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/zacharyburns/Documents/git/GettingStarted/node_modules/sha3
```

I suggest that we add support for the latest Node LTS - 12.x. In the interim until support can be added I suggest that we amend the docs with a note on which versions are currently supported.

**Comment by incrypto32** [comment]
Closing this because of the recent updates.
