### ISSUE TITLE
ByteArray.fromHexString: odd input length

### ISSUE THREAD

**Issue by olekspickle** [graphprotocol/support#52]
Apparently ByteArray.fromHexString("0x0") - is how you get input `0x0 has odd length` assert from graph-ts/ByteArray.fromHexString implementation.

Basically I have a [helper function](https://github.com/akropolisio/credit-pool-subgraph/blob/028f7f23687e7d560e6e9b1b9385016933e28f5f/src/utils.ts#L6) to construct hash out of two strings, and I am using it for `crypto.keccak256` input to concat two `ByteArray.fromHexString` outputs. 
And it fails to construct it from contract uint256 `0`.

Here is an illustration that it [should work](https://webassembly.studio/?f=td8a1g9py5)

**Comment by incrypto32** [comment]
Closing this because of the recent updates, this issue should be resolved by now. Feel free to reopen this issue if the problem still persists
