### ISSUE TITLE
ethereum namespace members not exported in templates

### ISSUE THREAD

**Issue by eternauta1337** [graphprotocol/support#60]
IDEs are not detecting properties from @graphprotocol/graph-ts/chain/ethereum/ts::Event

![Screenshot from 2020-05-19 14-33-13](https://user-images.githubusercontent.com/550409/82359103-d6df4500-99dd-11ea-9608-aff17e30a169.png)

Error: "Property 'address' does not exist on type 'Transfer'.ts(2339)"

Related, Event is not found in generated Event types:

![Screenshot from 2020-05-19 14-35-08](https://user-images.githubusercontent.com/550409/82359301-17d75980-99de-11ea-8800-404a3cbca1d1.png)

Tested in Vscode, vim and Webstorm.

I believe that the problem exists because Event, as with other objects, is declared in ethereum.ts, but not exported. The "ethereum" namespace is exported, but not its members. As soon as I export the members, the errors dissapear.

Curiously, code on master does seem to export the members: https://github.com/graphprotocol/graph-ts/blob/master/chain/ethereum.ts#L384

So, it seems that the version of graph-ts that ships with templates generated by graph-cli init has this problem

**Comment by Jannis** [comment]
Fixed via https://github.com/graphprotocol/graph-ts/pull/111 and released as part of https://github.com/graphprotocol/graph-ts/releases/tag/v0.18.1.
