### ISSUE TITLE
Is it possible to query with a nested where syntax?

### ISSUE THREAD

**Issue by max-block** [graphprotocol/support#61]
https://thegraph.com/explorer/subgraph/uniswap/uniswap-v2
I'm trying to find all swaps, where swap.pair.token0.symbol="USDC".

I've tried two queries, buy they don't work.
```
{
  swaps(where:{pair:{token0:{symbol:"USDC"}}}){
    pair{
      token0{
        symbol
      }
    }
    timestamp
  }
}
```
This query generates an error: Invalid value provided for argument `where`: Object({\"pair\": Object({\"token0\": Object({\"symbol\": String(\"USDC\")})})})

```
{
  swaps{
    pair{
      token0(where:{symbol:"USDC"}){
        symbol
      }
    }
    timestamp
  }
}
```
This query runs, but doesn't filter by symbol.

**Comment by leoyvens** [comment]
This is a known limitation

**Comment by heri16** [comment]
Any updates on this?

**Comment by illiablkcha** [comment]
there is not a way to solve the problem.

**Comment by illiablkcha** [comment]
it's a graphql bug.

**Comment by schmidsi** [comment]
@chenxiwang177 This is being worked on: https://github.com/graphprotocol/graph-node/pull/3184

**Comment by yuranich** [comment]
The above was merged year ago but syntax still doesn't work on uniswap v3
https://thegraph.com/hosted-service/subgraph/uniswap/uniswap-v3

Is it possible to do something about it?
