### ISSUE TITLE
Default example query for uniswap v2 in the explorer includes non-existing field

### ISSUE THREAD

**Issue by dutterbutter** [graphprotocol/support#68]
When visiting [Uniswap v2 on the explorer ](https://thegraph.com/explorer/subgraph/uniswap/uniswap-v2), the graphql example query includes a non-existing field, `pairs`. This is the default graphql presented and when you execute the query it fails. The default schema should be updated to remove the field `pairs`. Included output below and screen shot.

**Current Behaviour:**

Default Graphql schema:
```
{
  uniswapFactories(first: 5) {
    id
    pairCount
    pairs {
      id
    }
    totalVolumeUSD
  }
  tokens(first: 5) {
    id
    symbol
    name
    decimals
  }
}
```

Response:
```
{
  "errors": [
    {
      "locations": [
        {
          "column": 5,
          "line": 5
        }
      ],
      "message": "Type `UniswapFactory` has no field `pairs`"
    }
  ]
}
```

![Screen Shot 2020-11-22 at 11 09 53 AM](https://user-images.githubusercontent.com/29983536/99910396-5b738e80-2cb3-11eb-9143-2c09ac6b38e7.png)

Removing the field `pairs` in the graphql schema fixes the issue and returns the correct response.

**Comment by lutter** [comment]
Thanks for the report! I fixed that a few weeks ago, but forgot to note that on this ticket.
