### ISSUE TITLE
code: InvalidParams, message: "invalid argument 1: hex string without 0x prefix" use network=fantom

### ISSUE THREAD

**Issue by 0xCaviar** [graphprotocol/support#71]
![image](https://user-images.githubusercontent.com/77817341/109832726-99515d00-7c7b-11eb-9efb-689dfb059ffc.png)

when i use network=fantom. echo above error. why?

Web3Error(Rpc(Error { code: InvalidParams, message: "invalid argument 1: hex string without 0x prefix", data: None })))

the same code use network=mainnet is running ok. use fantom echo this error.

**Comment by leoyvens** [comment]
Fantom does not yet support EIP-1898 which we require for contract calls.

**Comment by leoyvens** [comment]
While they don't add support, graph-node could use calls by number for Fantom, possibly with a check like the one that was used for ganache https://github.com/graphprotocol/graph-node/blob/688f157021c936d92b7afc2474e716988647d709/chain/ethereum/src/ethereum_adapter.rs#L107.

**Comment by 0xCaviar** [comment]
ok, thanks so much. i will try and check.
