### ISSUE TITLE
Failed to upload subgraph to IPFS: Failed to upload file to IPFS: connect ETIMEDOUT 104.18.11.19:443

### ISSUE THREAD

**Issue by tmac2yt** [graphprotocol/support#73]
√ Compile subgraph
  Copy subgraph file build\schema.graphql
  Write subgraph file build\contract\abi\lend721.json
  Write subgraph manifest build\subgraph.yaml
√ Write compiled subgraph to build\
  Add file to IPFS build\schema.graphql
× Failed to upload subgraph to IPFS: Failed to upload file to IPFS: connect ETIMEDOUT 104.18.11.19:443
Error: Failed to upload file to IPFS: connect ETIMEDOUT 104.18.11.19:443
    at Compiler._uploadToIPFS (D:\projects\oortLending\.thegraph\node_modules\@graphprotocol\graph-cli\src\compiler.js:613:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by leoyvens** [comment]
Which was the IPFS node being used? This is a networking error to the IPFS node.

**Comment by incrypto32** [comment]
Closing this because of the recent updates, this issue should be resolved by now. Feel free to reopen this issue if the problem still persists
