### ISSUE TITLE
Missing trie node

### ISSUE THREAD

**Issue by Wetitpig** [graphprotocol/support#74]
I am trying to sync a [subgraph](https://thegraph.com/explorer/subgraph/wetitpig-cross-chain/streetswap?selected=logs) on thegraph.com, however it failed without any reason displayed in the console.

Further queries on the index API showed the following error:
```
{"data":{"indexingStatusForCurrentVersion":{"chains":[{"chainHeadBlock":{"number":"7902402"},"latestBlock":{"number":"4334195"}}],"fatalError":{"block":{"hash":"0xfa93e203e589349c1542953860dee19f2d7bfbd13162927537f51dff8e37f4ad","number":"4334198"},"handler":null,"message":"Ethereum node returned an error when calling function \"getPair\" of contract \"Factory\": RPC error: Error { code: ServerError(-32000), message: \"missing trie node 401182c349f38fedba89c8d8896c45f23a89d8baf33c99da84908c4ef9147d00 (path )\", data: None }\twasm backtrace:\t    0: 0x206c - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#call\t    1: 0x20b2 - <unknown>!src/types/templates/Pair/Factory/Factory#getPair\t    2: 0x22e2 - <unknown>!src/mappings/pricing/findEthPerToken\t    3: 0x25d5 - <unknown>!src/mappings/core/handleSync\t"},"health":"failed","synced":false}}
```

This seems to be a bug with the indexer, where some trie nodes were dropped. Is there a solution to this seemingly server-side error? Thank you!

**Comment by schmidsi** [comment]
Related: https://github.com/graphprotocol/support/issues/75

**Comment by azf20** [comment]
The BSC team are working on a proxy that will enable full archival support

**Comment by nftgeek** [comment]
Hello,  @azf20  @schmidsi   any update on this issue?  can't index bsc for days.  what went wrong?

**Comment by azf20** [comment]
hi @nftgeek - are you seeing the `missing trie node` error specifically, or a different BSC indexing error?

**Comment by nftgeek** [comment]
Hi @azf20   yes exactly.  we are seeing the `missing trie node` error.  is there any workaround?

**Comment by azf20** [comment]
@pranavdaa was working on this with the BSC team - is there any update here?

**Comment by koen84** [comment]
"missing try node" is an error generally associated with running a fast / full node, where archive node is required

**Comment by rhlsthrm** [comment]
I'm seeing the same error on my Arbitrum testnet subgraph: https://thegraph.com/legacy-explorer/subgraph/connext/nxtp-arbitrum-rinkeby?selected=logs

**Comment by schmidsi** [comment]
@rhlsthrm Regarding Arbitrum: We are working with them to find a solution here. Thanks for flagging this.

**Comment by schmidsi** [comment]
@rhlsthrm "Missing trie node" problem should be fixed on `arbitrum-rinkeby`. I quickly checked your subgraph and it looks good to me. Can you confirm this?

**Comment by rhlsthrm** [comment]
@schmidsi it is indeed fixed. Thank you for following up.

**Comment by schmidsi** [comment]
Hey, we have a better endpoint now for Binance Smart Chain that should support also blocks before 7796111. Can you please deploy a version of your subgraph that starts before that block and see, if that error is still around?

**Comment by GrooveWind** [comment]
@schmidsi I have same error info when my subgraph to be used in HECO Test Chain, will it be solved?

The error info:
`WARN Trying again after eth_call RPC call failed (attempt #10) with result Err(Web3Error(Rpc(Error { code: ServerError(-32000), message: "missing trie node 1b72217958305f516e55504c8eee45207ab987f83f5d8732f0d36efa4d793f7d (path )", data: None }))), block_hash: 0x9d2c2728b6f5093c217267b40cf77f1f81ca433c60eb3855fc37e982aa8685d5, block_number: 10513942, sgd: 1, subgraph_id: QmcLBZ7ddG95oNs7mud6QU9vwMpxjT6miV6DANWcX9rgAg, component: SubgraphInstanceManager`

**Comment by azf20** [comment]
Hey @GrooveWind - that is a problem with your HECO Test Chain node, you must ensure that it is an archival node.

Closing this issue as this was resolved for our BSC nodes, please do re-open if this error recurs for BSC subgraphs
