### ISSUE TITLE
ipfs Upload

### ISSUE THREAD

**Issue by ClownYar** [graphprotocol/support#79]
![1626317454(1)](https://user-images.githubusercontent.com/70617563/125720317-2388572e-a69a-4a61-815a-0f297a35cbc2.jpg)
I encountered this error when deploying the subgraph step, how can I solve this

**Comment by schmidsi** [comment]
This can happen some times. Can you just retry?

**Comment by schmidsi** [comment]
Closing this since it was an intermittent error back then. Feel free to reopen if it still exists.
