### ISSUE TITLE
Timeout error on a handler for Arbitrum Rinkeby

### ISSUE THREAD

**Issue by azf20** [graphprotocol/support#81]
Trigger processing is timing out on the Hosted Service, indexing Rinkeby Arbitrum. Error:

```
Subgraph instance failed to run: failed to process trigger: block #1707353 (0xfcf0…4c7f), transaction 496c4fab4bdadefbddfc4a9c98f939e52b7419ca4b151a027a1673def366b5c8: Handler 'handleTransactionPrepared' hit the timeout of '600' seconds: wasm trap: interrupt wasm backtrace: 0: 0xffffffff - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.Value#toBigInt 1: 0x1783 - <unknown>!src/mapping/handleTransactionPrepared , code: SubgraphSyncingFailure
```

Subgraph: [QmTUxX5vivns468Pv8Lk5DArvK3KWcPTERMbWKWos4gdFu](https://thegraph.com/legacy-explorer/subgraph/connext/nxtp-arbitrum-rinkeby?selected=logs)
Mapping: https://github.com/connext/nxtp/blob/main/packages/subgraph/src/mapping.ts#L64

Developer has tried to redeploy - same error, **but on a different block**

**Comment by samajammin** [comment]
Hey folks! We're seeing the same issue here: https://github.com/ethereum/clrfund/issues/402

Were you able to resolve this issue, or identify the source of the problem? It seems The Graph limits handler execution to 600 seconds. Is the only way to solve this to optimize/shorten the handler function?

Thanks in advance!

**Comment by azf20** [comment]
thanks @samajammin - we saw intermittent issues with Arbitrum `eth_call` timeouts, though that was (largely) addressed by a change to the Arbitrum node. Are you still seeing this issue, and do you have the specific call that takes a long time?

**Comment by samajammin** [comment]
Good news - we've been unable to reproduce this error. We've deployed multiple new subgraph instances to RinkArby and it didn't throw any errors. We closed out https://github.com/ethereum/clrfund/issues/402

**Comment by azf20** [comment]
OK great, closing this issue, thanks @samajammin!
