### ISSUE TITLE
Gateway: Failed to get entities from store

### ISSUE THREAD

**Issue by schmidsi** [graphprotocol/support#83]
Error message:
```
Failed to get entities from store: relation "sgd86.project" does not exist, query = "/* qid: 30079ddb410a63f2-fa18b9efba7cf9d9 */\nselect 'Project' as entity, to_jsonb(c.*) as data from (select  * \n  from \"sgd86\".\"project\" c\n where c.\"block_range\" @> $1 and (\"org\" = $2)\n\n order by \"id\"\n limit 100) c -- binds: [13142350, \"0x8152237402e0f194176154c3a6ea1eb99b611482\"]
```

Report on Discord: https://discord.com/channels/438038660412342282/438070183794573313/882916858838282290

Reproduction steps:
- Go to: https://thegraph.com/explorer/subgraph?id=0x2f0963e77ca6ac0c2dad1bf4147b6b40e0dd8728-0&view=Playground
- Run the query several times

<img width="1552" alt="Screenshot 2021-09-02 at 17 34 04" src="https://user-images.githubusercontent.com/103280/131876264-510ee722-cff5-46e5-94be-0971880a845c.png">

**Comment by lutter** [comment]
This looks like an issue with a specific indexer; the error message indicates that something is seriously wrong with the database setup of that indexer, but it's not possible to tell from the error message which indexer that is. Without knowing which indexer is returning that error, it's not possible to further investigate what got that indexer into that state.

@Jannis or @fordN: any ideas on how we can figure out which indexer is returning these errors?

**Comment by incrypto32** [comment]
Closing this because of the recent updates, this issue should be resolved by now. Feel free to reopen this issue if the problem still persists
