### ISSUE TITLE
Transactions not found with filter

### ISSUE THREAD

**Issue by jacko06v** [graphprotocol/support#85]
i'm making a subgraph for a token, i made a query to take all the transactions made with that tokens, it works fine
the graphql schema is: 

`type Transaction @entity {
  id: ID!
  Amount: BigInt!
  Sender: String!
  Receiver: String!
  MilliDate: BigInt!
}`

where the ID is the transaction hash

now i want to filter the transactions to get only transactions with a specific Receiver

i did: 

`{
  transactions(where: {Receiver: "0x8ABa7FBaE92012c8A86C5182538A5dE11039Dad1"}){
    id
    Amount
    MilliDate
    Sender
    Receiver
  }
}`

for some address it works, for other address not.

<img width="1440" alt="Schermata 2021-10-08 alle 10 56 29" src="https://user-images.githubusercontent.com/76396947/136528490-8f880b08-5a78-4620-8379-b068ea5e1fb7.png">

<img width="1440" alt="Schermata 2021-10-08 alle 10 56 58" src="https://user-images.githubusercontent.com/76396947/136528521-d5d2ba58-5bd5-4e6e-b7ef-a73e3a100c47.png">

i'm sure that the address not found as reciver, have received some tokens, so i searched for the id (transaction hash of the tranfer) doing this: 

`{
  transaction(id: "0xff089a3dcc62797bd90de39d92816c4b74b22b62b51b8494ae4178ee7fb28f2b" ){
    id
    Amount
    MilliDate
    Sender
    Receiver
  }
}`

the result:

<img width="1440" alt="Schermata 2021-10-08 alle 11 00 51" src="https://user-images.githubusercontent.com/76396947/136528976-ca7fb33c-7adc-499f-ba4d-8886008c267d.png">

and now i can find the transaction where it is the receiver... why it doesn't work with "where" ? i'm wrong in something?

**Comment by azf20** [comment]
Hey @jacko06v - you need to lower-case the address in the where clause, and this should work. Closing, do re-open if that doesn't resolve the issue!
