### ISSUE TITLE
missing trie node

### ISSUE THREAD

**Issue by pwilczynskiclearcode** [graphprotocol/support#86]
Hey,
I'm trying to run a self-hosted graph-node but my subgraph stucks on `8625140` mainnet block:
```
INFO Possible reorg detected, retrying, error: failed to process trigger: block #8625140 (0xeb12…311d), transaction ecafa126c0c1e23c99d3b7acf79f57c4e2abe5bab35a38092bb31bc81965e2fa: Ethereum node returned an error when calling function \"name\" of contract \"ERC20Detailed\": RPC error: Error { code: ServerError(-32000), message: \"missing trie node 1ae2ebe56fa49ba66f90923ec87bb6a7fe1e88007c293c4b9f2aa3ca8fd14a42 (path )\", data: None }\n",
```
Is there any way to skip this particular transaction in the subgraph? Or fix the issue?

**Comment by schmidsi** [comment]
Hi @pwilczynskiclearcode, are you indexing Ethereum mainnet? Are you running your own node or are you using a JSON RPC provider like Alchemy or Infura? If you run our own node, which one do you run? Is it an archive node or just a full node? You need to have an archive node in order to run graph-node.

**Comment by pwilczynskiclearcode** [comment]
Hi @schmidsi 
I'm connected to Infura's `mainnet` in archive mode
```
    "log": "Dec 07 23:02:54.311 INFO Creating transport, capabilities: archive, traces, url: https://mainnet.infura.io/v3/XXXXXXXXXXXXXX, provider: mainnet-rpc-0\n",
```
Do you think that it's Infura's issue and I should use another provider?

**Comment by schmidsi** [comment]
`capabilities: archive, traces` does not mean that graph-node has detected those capabilities. It simply assumes that they are present in given endpoint. As far as I know, Infura endpoints by default are full-nodes not archive nodes. Especially the free ones. I know that there are people able to run a graph-node with Infura-endpoints. But you can try Alchemy.

On another note: Did you try to deploy your subgraph to the [hosted service](http://thegraph.com/hosted-service/)? Does it sync there?

**Comment by pwilczynskiclearcode** [comment]
Yes, my subgraph works on hosted service.
I switched to Alechemy and it processed block that was previously stuck on Infura
Thank you!

**Comment by schmidsi** [comment]
Alright, thanks for the update. Closing this issue then. Feel free to reopen it if this is not resolved for you.
