### ISSUE TITLE
Can't access hosted service, gives time out error

### ISSUE THREAD

**Issue by SachiniPiyumali** [graphprotocol/support#89]
- Can't access the subgraph in hosted service
- It keeps loading and gives time out error

**Comment by schmidsi** [comment]
Hey @SachiniPiyumali, so sorry for the late reply. We improved our infrastructure quite a bit and this should not be an issue anymore. Can you please try again and confirm? Otherwise happy to dive deeper into this and fix it. Feel free to reopen this ticket.
