### ISSUE TITLE
Missing trie node on Avalanche

### ISSUE THREAD

**Issue by jensonb** [graphprotocol/support#90]
Hi team,

We have an Avalanche Hosted Service subgraph at `QmakLR16hqvPVh2bsScvYa91uUK7B4J41hNTrVwuq7PYpY`. Lately, it has been stalling out while re-indexing with the following error:

> Possible reorg detected, retrying, error: failed to process trigger: block #10765612 (0x4278…2b1c), transaction 8a5d5836fb0fe5bef9d4f25bc9b083c9ad6762ffa71cb24ca6d44ded27e08cdb: Ethereum node returned an error when calling function "name" of contract "ERC20": RPC error: Error { code: ServerError(-32000), message: "missing trie node 69f62b943f0d9aa5c9a35a689f6cfa066b30ab5bd605148ec72f0d82fbc64fee (path )", data: None } wasm backtrace: 0: 0x3f3c - <unknown>!src/mappings/Kernel/initializePlatformData 1: 0x449d - <unknown>!src/mappings/Kernel/handleTokenAdded 2: 0x47f4 - <unknown>!src/mappings/Kernel/handleTokenAddedLegacy , block_hash: 0x427815eeda03895b1370cbebe2322621ea32413195a5496b79278e47f2352b1c, block_number: 10765612

Deploying a new version to trigger re-indexing does not seem to help.

After looking at past issues like #75, it would seem that this is probably an issue on thegraph's side with the indexing nodes? Appreciate your time and the great product you guys have made!

**Comment by schmidsi** [comment]
Hey I can not find a subgraph with deploymentId `QmakLR16hqvPVh2bsScvYa91uUK7B4J41hNTrVwuq7PYpY` on the hosted service. Did you deploy a new version? Is this issue resolved? If not, feel free to reopen it.
