### ISSUE TITLE
RPC rate limit on Fantom

### ISSUE THREAD

**Issue by jensonb** [graphprotocol/support#91]
Hi Team,

We have a Fantom Hosted Service subgraph at `Qmb9C4bgHf7rCmWCuw6F3q8Fra6UX6UyhSmN77ZoZg2KM8`. Lately, it has been indexing extremely slowly, while returning a rate limit error:

> Trying again after eth_getLogs RPC call for block range: [31240791..31240800] failed (attempt #10) with result Err(Transport("Unexpected response status code: 429 Too Many Requests")), component: BlockStream

After running for several hours, the indexing algorithm has bumped the block range down to 10 blocks and is still hitting the rate limit error.

![image](https://user-images.githubusercontent.com/19617447/156896016-893f9b1d-18e9-4946-88a2-1f08bdc9623b.png)

Our subgraph does _NOT_ use any call handlers, only event handlers.
It _DOES_ make archival contract calls while handling some events.

Any advice on whether this is a service issue, or if there are better practices we need to follow to ensure the performance of our subgraph?

**Comment by schmidsi** [comment]
Hi @jensonb, sorry to hear that you had bad experiences with Fantom. There was actually an issue with wrong rate limiting which we were able to resolve. Is this still an issue for you? If yes, feel free to reopen this ticket.

Btw: Can't find subgraph `Qmb9C4bgHf7rCmWCuw6F3q8Fra6UX6UyhSmN77ZoZg2KM8` on the hosted service anymore.
