### ISSUE TITLE
Pending Version won’t swap to Current Version

### ISSUE THREAD

**Issue by DroidMuncher** [graphprotocol/support#92]
Hi devs

You can see my [SubGraph here](https://thegraph.com/hosted-service/subgraph/droidmuncher/robo-vault-dev-subgraph).

I have a Pending Version that has successfully synced, although it will not swap over to the Current Version. My understand is that it should automatically replace the Current Version once syncing is complete. 

It finished syncing around 6 days ago. I have tried to redeploy without any luck.

Any ideas on whats going on?

Thanks

**Comment by schmidsi** [comment]
Sorry for the late reply here. There was a bug with exactly this switch from pending to current which should be resolved by now. Closing this since your subgraph does not have a pending version anymore. Feel free to reopen if it is not resolved.
