### ISSUE TITLE
Near. Error deploying the subgraph with code 524

### ISSUE THREAD

**Issue by werber** [graphprotocol/support#93]
Couldn't find any relevant info regarding near mainnet and deploying issue. I'm trying to deploy graph to near mainnet.

In subgraph.yaml I use network like this:
```
network: near-mainnet
```
as it described in docs.

What I do when deploying is simple command:
```
graph deploy --node https://api.thegraph.com/deploy/ werber/MY_GRAPH_NAME
```

What I get in the end:
```
 HTTP error deploying the subgraph 524
```

Build hash is: QmYCeSXpkpHAt1NLrQzYT8yYyGM1UuUNcAjhKcrDzU5Ukm (this is when I build graph locally, in case this is needed for debugging). On Graph Hosted Service nothing appears or being deployed.

**Comment by schmidsi** [comment]
These 524 errors are intermittent. We are monitoring it and it should have become better recently. Just trying again several times usually makes the trick. Feel free to reopen this issue if it is not resolved for you.
