### ISSUE TITLE
BSC subgraph with callHandler cause error

### ISSUE THREAD

**Issue by mohandesjiri** [graphprotocol/support#95]
I try to deploy a subgraph on the BSC chain and face this error:

`
Failed to start subgraph, code: SubgraphStartFailure, error: expected triggers adapter that matches deployment QmS58kNTGg4VYPNMEH53JymEKjcrUtCzRQmNS3pkNMTJMD[279681] with required capabilities: traces: A matching Ethereum network with NodeCapabilities { archive: false, traces: true } was not found.
`

When I deploy this subgraph to `mainnet` or change a subgraph by deleting the `callHandler` everything works fine.

**Comment by incrypto32** [comment]
@mohandesjiri Call handlers are not supported on all chains including bsc.

Closing this issue.Feel free to reopen if you have further questions

**Comment by mohandesjiri** [comment]
@incrypto32 
Thanks for your response.
As We can see in the error message subgraph could not find a node with traces: true.
Would you mind helping me to catch and resolve this error?

**Comment by incrypto32** [comment]
@mohandesjiri  As imentioned callhandlers are not available on bsc removing it will resolve this issue

**Comment by mohandesjiri** [comment]
@incrypto32 
 you said first "Call handlers are supported on all chains including bsc."
Anyway, is there any plan to provide this feature on BSC chain?

**Comment by incrypto32** [comment]
@mohandesjiri Appologies for the typo. Edited it.. I meant its not supported on all chains. And bsc is not supported

**Comment by schmidsi** [comment]
You are right, the error message does not really talk about the underlying problem: In order to have `callHandlers` the underlying JSON RPC provider needs to implement the so called "Parity Traces" feature as described here: https://openethereum.github.io/JSONRPC-trace-module. Unfortunately, no available node for BSC is capable of doing this.
