### ISSUE TITLE
Contract Events, Update Struct in Array Solidity

### ISSUE THREAD

**Issue by ratio-dev** [graphprotocol/support#96]
I have structs in the smart contract. This is struct include "status" row (active, close and etc) how i can find changes? I can change the events in the grapql or something?

event Create()
event Close()

**Comment by incrypto32** [comment]
@ratio-dev Can you elaborate a bit more on what you are trying to achieve? Maybe share some code?

If you are trying to update some entity when the status field in the struct is changed. You can do it if an event like `StatusChanged` is emitted. You can create an event handler to update the entity whenever the status is changed

**Comment by ratio-dev** [comment]
Yes, i tried update  a some entity. This is code works for me mapping.ts

```
export function handleCloseRequest (event: CloseRequest) : void {

   let _row = Create.load(event.params._index.toString());

   if(_row !== null) {
     _row._status = event.params._status;
     _row.save();
   };

};
```
