### ISSUE TITLE
Pagination Pages

### ISSUE THREAD

**Issue by ratio-dev** [graphprotocol/support#97]
How i can implement pagination to pages ? At now i find only "skip" and "first" parametres

**Comment by incrypto32** [comment]
@ratio-dev You could implement basic pagination with `skip` and `first`
Also you can base queries on an attribute and filter by that attribute as mentioned [here](https://thegraph.com/docs/en/developer/graphql-api/#example-4)

**Comment by ratio-dev** [comment]
@incrypto32  Thanks i created a base pagination, but i think it is very simple. At least backend solutions must have a total counter

**Comment by incrypto32** [comment]
@ratio-dev That's where you can base the queries on last recieved objects ID as i [linked](https://thegraph.com/docs/en/developer/graphql-api/#example-4) in the previous comment. Also having a single counter variable to keep track also is not a big overhead
