### ISSUE TITLE
venus subgraph not working

### ISSUE THREAD

**Issue by wxw1111** [graphprotocol/support#98]
https://thegraph.com/hosted-service/subgraph/venusprotocol/venus-subgraph
"errors": [{"message": "indexing_error"}]

**Comment by incrypto32** [comment]
@wxw1111 
You can check you subgraphs health as described [here](https://thegraph.com/docs/en/hosted-service/deploy-subgraph-hosted/#checking-subgraph-health). This query will return a fatalErrors field which will contain the error message which caused it to fail.

Here you go I've done the query and this is the error that caused your subgraph to fail. You can address the issues and redeploy the subgraph now
```attempted to divide BigDecimal `0` by zero\twasm backtrace:\t    0: 0x12a6 - <unknown>!<wasm function 37>\t    1: 0x303a - <unknown>!<wasm function 171>\t    2: 0x33ab - <unknown>!<wasm function 174>\t in handler `handleTransfer` at block #17821323 (6e8a6ea2519b87afa3888fc96f4c285e65f06a99d71ccae312c2597924f7033f)```


I'm closing this issue. Feel free to drop a message in our discord if you need further assistance.
